export const INITIAL_REQUEST_RESULTS = [
  {
    "vote_count": 267,
    "id": 297802,
    "video": false,
    "vote_average": 7,
    "title": "Aquaman",
    "popularity": 528.904,
    "poster_path": "/ydUpl3QkVUCHCq1VWvo2rW4Sf7y.jpg",
    "original_language": "en",
    "original_title": "Aquaman",
    "genre_ids": [28, 14, 878, 12, 10749],
    "backdrop_path": "/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg",
    "adult": false,
    "overview": "The film reveals the origin story of half-human, half-Atlantean Arthur Curry and takes him on the journey of his lifetime—one that will not only force him to face who he really is, but to discover if he is worthy of who he was born to be… a king.",
    "release_date": "2018-12-07"
  }, {
    "vote_count": 101,
    "id": 418970,
    "video": false,
    "vote_average": 6.5,
    "title": "Just to Be Sure",
    "popularity": 358.88,
    "poster_path": "/naSY3Msahk7cOpVJDJQADfWSYkk.jpg",
    "original_language": "fr",
    "original_title": "Ôtez-moi d'un doute",
    "genre_ids": [18, 35],
    "backdrop_path": "/4XUdDDnMCgjdy5rXmxEjo8n62BN.jpg",
    "adult": false,
    "overview": "Erwan, a strapping Breton who clears mines for a living, is shaken when he discovers that his father is not his father. Despite his affection for the man who raised him, he quietly sets out to find his biological father, and succeeds in locating Joseph, an endearing old codger he takes a liking to. Just when things look settled, another unexpected “bomb” hits Erwan in the form of Anna, an elusive nymph.",
    "release_date": "2017-09-06"
  }, {
    "vote_count": 2183,
    "id": 338952,
    "video": false,
    "vote_average": 7,
    "title": "Fantastic Beasts: The Crimes of Grindelwald",
    "popularity": 286.684,
    "poster_path": "/uyJgTzAsp3Za2TaPiZt2yaKYRIR.jpg",
    "original_language": "en",
    "original_title": "Fantastic Beasts: The Crimes of Grindelwald",
    "genre_ids": [10751, 14, 12],
    "backdrop_path": "/wDN3FIcQQ1HI7mz1OOKYHSQtaiE.jpg",
    "adult": false,
    "overview": "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
    "release_date": "2018-11-14"
  }, {
    "vote_count": 201,
    "id": 480530,
    "video": false,
    "vote_average": 6.7,
    "title": "Creed II",
    "popularity": 280.811,
    "poster_path": "/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg",
    "original_language": "en",
    "original_title": "Creed II",
    "genre_ids": [18, 28],
    "backdrop_path": "/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg",
    "adult": false,
    "overview": "Follows Adonis Creed's life inside and outside of the ring as he deals with new found fame, issues with his family, and his continuing quest to become a champion.",
    "release_date": "2018-11-20"
  }, {
    "vote_count": 16,
    "id": 503314,
    "video": false,
    "vote_average": 7.6,
    "title": "Dragon Ball Super: Broly",
    "popularity": 250.204,
    "poster_path": "/518jdIQHCZmYqIcNCaqbZuDRheV.jpg",
    "original_language": "ja",
    "original_title": "Dragon Ball Super: Broly",
    "genre_ids": [28, 16, 878],
    "backdrop_path": "/6OTRuxpwUUGbmCX3MKP25dOmo59.jpg",
    "adult": false,
    "overview": "Earth is peaceful following the Tournament of Power. Realizing that the universes still hold many more strong people yet to see, Goku spends all his days training to reach even greater heights. Then one day, Goku and Vegeta are faced by a Saiyan called 'Broly' who they've never seen before. The Saiyans were supposed to have been almost completely wiped out in the destruction of Planet Vegeta, so what's this one doing on Earth? This encounter between the three Saiyans who have followed completely different destinies turns into a stupendous battle, with even Frieza (back from Hell) getting caught up in the mix.",
    "release_date": "2018-12-14"
  }, {
    "vote_count": 3241,
    "id": 335983,
    "video": false,
    "vote_average": 6.5,
    "title": "Venom",
    "popularity": 248.153,
    "poster_path": "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
    "original_language": "en",
    "original_title": "Venom",
    "genre_ids": [878],
    "backdrop_path": "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
    "adult": false,
    "overview": "Eddie Brock is a reporter—investigating people who want to go unnoticed. But after he makes a terrible discovery at the Life Foundation, he begins to transform into ‘Venom’.  The Foundation has discovered creatures called symbiotes, and believes they’re the key to the next step in human evolution. Unwittingly bonded with one, Eddie discovers he has incredible new abilities—and a voice in his head that’s telling him to embrace the darkness.",
    "release_date": "2018-10-03"
  }, {
    "vote_count": 177,
    "id": 428078,
    "video": false,
    "vote_average": 6.2,
    "title": "Mortal Engines",
    "popularity": 222.341,
    "poster_path": "/uXJVpPXxZO4L8Rz3IG1Y8XvZJcg.jpg",
    "original_language": "en",
    "original_title": "Mortal Engines",
    "genre_ids": [878, 28, 12],
    "backdrop_path": "/rxYG6Sj95as9rv9wKIHUx6ATWd3.jpg",
    "adult": false,
    "overview": "Set in a world many thousands of years in the future. Earth’s cities now roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive Traction Cities, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the Outlands who will change the course of his life forever.",
    "release_date": "2018-12-06"
  }, {
    "vote_count": 134,
    "id": 324857,
    "video": false,
    "vote_average": 8.5,
    "title": "Spider-Man: Into the Spider-Verse",
    "popularity": 190.056,
    "poster_path": "/laMM4lpQSh5z6KIBPwWogkjzBVQ.jpg",
    "original_language": "en",
    "original_title": "Spider-Man: Into the Spider-Verse",
    "genre_ids": [28, 12, 16, 878, 35],
    "backdrop_path": "/e7CE5vx4KqUuz0peKdHRVZB0Pn8.jpg",
    "adult": false,
    "overview": "Miles Morales is juggling his life between being a high school student and being Spider-Man. However, when Wilson \"Kingpin\" Fisk uses a super collider, another Spider-Man from another dimension, Peter Parker, accidentally winds up in Miles' dimension. As Peter trains Miles to become a better Spider-Man, they are soon joined by four other Spider-Men from across the \"Spider-Verse\". As all these clashing dimensions start to tear Brooklyn apart, Miles must help the others stop Fisk and return everyone to their own dimensions.",
    "release_date": "2018-12-07"
  }, {
    "vote_count": 35,
    "id": 424783,
    "video": false,
    "vote_average": 5.9,
    "title": "Bumblebee",
    "popularity": 169.462,
    "poster_path": "/sG6n4ei1F0kVQtTs3fAjDghngpa.jpg",
    "original_language": "en",
    "original_title": "Bumblebee",
    "genre_ids": [28, 12, 878],
    "backdrop_path": "/wtZj5nn6hVwgakPdg6y6gm3eFXU.jpg",
    "adult": false,
    "overview": "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.  When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.",
    "release_date": "2018-12-15"
  }, {
    "vote_count": 389,
    "id": 407436,
    "video": false,
    "vote_average": 6.8,
    "title": "Mowgli: Legend of the Jungle",
    "popularity": 150.479,
    "poster_path": "/clRnzMsFoMIdC7I5JsG6dnnHH8l.jpg",
    "original_language": "en",
    "original_title": "Mowgli: Legend of the Jungle",
    "genre_ids": [12, 18],
    "backdrop_path": "/2CECgwgaqfrkBigDe7ZadUhE2td.jpg",
    "adult": false,
    "overview": "A human child raised by wolves, must face off against a menacing tiger named Shere Khan, as well as his own origins.",
    "release_date": "2018-11-25"
  }, {
    "vote_count": 1182,
    "id": 346910,
    "video": false,
    "vote_average": 5.2,
    "title": "The Predator",
    "popularity": 145.642,
    "poster_path": "/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg",
    "original_language": "en",
    "original_title": "The Predator",
    "genre_ids": [878, 28, 53, 12],
    "backdrop_path": "/f4E0ocYeToEuXvczZv6QArrMDJ.jpg",
    "adult": false,
    "overview": "When a kid accidentally triggers the universe's most lethal hunters' return to Earth, only a ragtag crew of ex-soldiers and a disgruntled female scientist can prevent the end of the human race.",
    "release_date": "2018-09-05"
  }, {
    "vote_count": 988,
    "id": 369972,
    "video": false,
    "vote_average": 7.1,
    "title": "First Man",
    "popularity": 145.115,
    "poster_path": "/i91mfvFcPPlaegcbOyjGgiWfZzh.jpg",
    "original_language": "en",
    "original_title": "First Man",
    "genre_ids": [36, 18],
    "backdrop_path": "/z1FkoHO7bz40S4JiptWHSYoPpxq.jpg",
    "adult": false,
    "overview": "A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon on July 20, 1969.",
    "release_date": "2018-10-11"
  }, {
    "vote_count": 2629,
    "id": 353081,
    "video": false,
    "vote_average": 7.2,
    "title": "Mission: Impossible - Fallout",
    "popularity": 131.137,
    "poster_path": "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    "original_language": "en",
    "original_title": "Mission: Impossible - Fallout",
    "genre_ids": [28, 53, 12],
    "backdrop_path": "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg",
    "adult": false,
    "overview": "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
    "release_date": "2018-07-13"
  }, {
    "vote_count": 9907,
    "id": 299536,
    "video": false,
    "vote_average": 8.3,
    "title": "Avengers: Infinity War",
    "popularity": 128.043,
    "poster_path": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "original_language": "en",
    "original_title": "Avengers: Infinity War",
    "genre_ids": [12, 28, 14],
    "backdrop_path": "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
    "adult": false,
    "overview": "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    "release_date": "2018-04-25"
  }, {
    "vote_count": 420,
    "id": 360920,
    "video": false,
    "vote_average": 6.3,
    "title": "The Grinch",
    "popularity": 115.806,
    "poster_path": "/lCfKAAFyANPFn04xOPqazd8jwnc.jpg",
    "original_language": "en",
    "original_title": "The Grinch",
    "genre_ids": [16, 10751, 35, 14],
    "backdrop_path": "/juc9wt7Eh2IarLL5S1yQ1a21O1A.jpg",
    "adult": false,
    "overview": "The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.",
    "release_date": "2018-11-08"
  }, {
    "vote_count": 339,
    "id": 454293,
    "video": false,
    "vote_average": 6.1,
    "title": "Night School",
    "popularity": 113.973,
    "poster_path": "/xjsJTVWZYxeP89fwH17rsVvhPAe.jpg",
    "original_language": "en",
    "original_title": "Night School",
    "genre_ids": [35],
    "backdrop_path": "/eiUO8svuxMv16wvZsxubNLb5wNL.jpg",
    "adult": false,
    "overview": "Teddy Walker is a successful salesman whose life takes an unexpected turn when he accidentally blows up his place of employment. Forced to attend night school to get his GED, Teddy soon finds himself dealing with a group of misfit students, his former high school nemesis and a feisty teacher who doesn't think he's too bright.",
    "release_date": "2018-09-27"
  }, {
    "vote_count": 1280,
    "id": 345887,
    "video": false,
    "vote_average": 6.3,
    "title": "The Equalizer 2",
    "popularity": 113.784,
    "poster_path": "/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg",
    "original_language": "en",
    "original_title": "The Equalizer 2",
    "genre_ids": [53, 28, 80],
    "backdrop_path": "/z7noaCJ4KtmhwHw7QcNtnMMo4Qy.jpg",
    "adult": false,
    "overview": "Robert McCall, who serves an unflinching justice for the exploited and oppressed, embarks on a relentless, globe-trotting quest for vengeance when a long-time girl friend is murdered.",
    "release_date": "2018-07-19"
  }, {
    "vote_count": 531,
    "id": 484247,
    "video": false,
    "vote_average": 6.4,
    "title": "A Simple Favor",
    "popularity": 107.968,
    "poster_path": "/aIYsjQM0piKc0ibPBCTWv3sqshj.jpg",
    "original_language": "en",
    "original_title": "A Simple Favor",
    "genre_ids": [53, 80, 9648, 35, 18],
    "backdrop_path": "/xXGNyEG2v48q0bVR4AH4Vca2yvy.jpg",
    "adult": false,
    "overview": "Stephanie, a dedicated mother and popular vlogger, befriends Emily, a mysterious upper-class woman whose son Nicky attends the same school than Miles, Stephanie's son. When Emily asks her to pick up Nicky from school and then disappears, Emily wonders what has happened to her friend, so she undertakes an investigation which will dive her deep in Emily's cloudy past.",
    "release_date": "2018-08-29"
  }, {
    "vote_count": 2514,
    "id": 424694,
    "video": false,
    "vote_average": 8.2,
    "title": "Bohemian Rhapsody",
    "popularity": 103.542,
    "poster_path": "/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
    "original_language": "en",
    "original_title": "Bohemian Rhapsody",
    "genre_ids": [18, 10402],
    "backdrop_path": "/pbXgLEYh8rlG2Km5IGZPnhcnuSz.jpg",
    "adult": false,
    "overview": "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
    "release_date": "2018-10-24"
  }, {
    "vote_count": 44,
    "id": 438808,
    "video": false,
    "vote_average": 5.7,
    "title": "White Boy Rick",
    "popularity": 102.07,
    "poster_path": "/l15r2aLqdifXM9GFsJLkOq5Y8SI.jpg",
    "original_language": "en",
    "original_title": "White Boy Rick",
    "genre_ids": [18, 80],
    "backdrop_path": "/iphqiuA8HJg15Haw4Hkk2iyhWRo.jpg",
    "adult": false,
    "overview": "The story of teenager, Richard Wershe Jr., who became an undercover informant for the police during the 1980s and was ultimately arrested for drug-trafficking and sentenced to life in prison.",
    "release_date": "2018-09-14"
  }
];
export const RESULT_QUERY_a = [
  {
    "vote_count": 543,
    "id": 484247,
    "video": false,
    "vote_average": 6.4,
    "title": "A Simple Favor",
    "popularity": 98.505,
    "poster_path": "/aIYsjQM0piKc0ibPBCTWv3sqshj.jpg",
    "original_language": "en",
    "original_title": "A Simple Favor",
    "genre_ids": [53, 80, 9648, 35, 18],
    "backdrop_path": "/xXGNyEG2v48q0bVR4AH4Vca2yvy.jpg",
    "adult": false,
    "overview": "Stephanie, a dedicated mother and popular vlogger, befriends Emily, a mysterious upper-class woman whose son Nicky attends the same school than Miles, Stephanie's son. When Emily asks her to pick up Nicky from school and then disappears, Emily wonders what has happened to her friend, so she undertakes an investigation which will dive her deep in Emily's cloudy past.",
    "release_date": "2018-08-29"
  }, {
    "vote_count": 2152,
    "id": 332562,
    "video": false,
    "vote_average": 7.4,
    "title": "A Star Is Born",
    "popularity": 51.118,
    "poster_path": "/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
    "original_language": "en",
    "original_title": "A Star Is Born",
    "genre_ids": [18, 10402, 10749],
    "backdrop_path": "/840rbblaLc4SVxm8gF3DNdJ0YAE.jpg",
    "adult": false,
    "overview": "Seasoned musician Jackson Maine discovers—and falls in love with—struggling artist Ally. She has just about given up on her dream to make it big as a singer—until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
    "release_date": "2018-10-03"
  }, {
    "vote_count": 1215,
    "id": 381289,
    "video": false,
    "vote_average": 7.1,
    "title": "A Dog's Purpose",
    "popularity": 34.561,
    "poster_path": "/3jcNvhtVQe5Neoffdic39fRactM.jpg",
    "original_language": "en",
    "original_title": "A Dog's Purpose",
    "genre_ids": [35, 18, 10751, 14],
    "backdrop_path": "/2ddVTlMyATZdvUHE7DPExA2X6xF.jpg",
    "adult": false,
    "overview": "A dog goes on quest to discover his purpose in life over the course of several lifetimes with multiple owners.",
    "release_date": "2017-01-19"
  }, {
    "vote_count": 2056,
    "id": 17979,
    "video": false,
    "vote_average": 6.7,
    "title": "A Christmas Carol",
    "popularity": 37.145,
    "poster_path": "/jeOCcjUAcSYleVwhsaKEPT4CYwF.jpg",
    "original_language": "en",
    "original_title": "A Christmas Carol",
    "genre_ids": [16, 18, 10751, 27],
    "backdrop_path": "/GtwSStViUdhKGf0d7tCkR7alKV.jpg",
    "adult": false,
    "overview": "Miser Ebenezer Scrooge is awakened on Christmas Eve by spirits who reveal to him his own miserable existence, what opportunities he wasted in his youth, his current cruelties, and the dire fate that awaits him if he does not change his ways. Scrooge is faced with his own story of growing bitterness and meanness, and must decide what his own future will hold: death or redemption.",
    "release_date": "2009-11-04"
  }, {
    "vote_count": 755,
    "id": 707,
    "video": false,
    "vote_average": 6.1,
    "title": "A View to a Kill",
    "popularity": 14.991,
    "poster_path": "/veDMW7eX6tat86EapsvGEICJ8Tq.jpg",
    "original_language": "en",
    "original_title": "A View to a Kill",
    "genre_ids": [12, 28, 53],
    "backdrop_path": "/9SudvdR6HYtgTqMz17RYXdWuTUl.jpg",
    "adult": false,
    "overview": "A newly developed microchip designed by Zorin Industries for the British Government that can survive the electromagnetic radiation caused by a nuclear explosion has landed in the hands of the KGB. James Bond must find out how and why. His suspicions soon lead him to big industry leader Max Zorin.",
    "release_date": "1985-05-24"
  }, {
    "vote_count": 195,
    "id": 438590,
    "video": false,
    "vote_average": 5.4,
    "title": "A-X-L",
    "popularity": 22.06,
    "poster_path": "/9kB56ZdMB6RgY5QtX9Bar45jCeI.jpg",
    "original_language": "en",
    "original_title": "A-X-L",
    "genre_ids": [878, 28, 12, 10751],
    "backdrop_path": "/l1nYo0yzKjf84atnBDbx0do16vQ.jpg",
    "adult": false,
    "overview": "The life of a teenage boy is forever altered by a chance encounter with cutting edge military technology.",
    "release_date": "2018-08-16"
  }, {
    "vote_count": 3980,
    "id": 447332,
    "video": false,
    "vote_average": 7.2,
    "title": "A Quiet Place",
    "popularity": 25.927,
    "poster_path": "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    "original_language": "en",
    "original_title": "A Quiet Place",
    "genre_ids": [18, 27, 53, 878],
    "backdrop_path": "/roYyPiQDQKmIKUEhO912693tSja.jpg",
    "adult": false,
    "overview": "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    "release_date": "2018-04-03"
  }, {
    "vote_count": 2703,
    "id": 348350,
    "video": false,
    "vote_average": 6.6,
    "title": "Solo: A Star Wars Story",
    "popularity": 42.824,
    "poster_path": "/3IGbjc5ZC5yxim5W0sFING2kdcz.jpg",
    "original_language": "en",
    "original_title": "Solo: A Star Wars Story",
    "genre_ids": [28, 12, 878],
    "backdrop_path": "/bJekWFxi4FwojQbKfTaW3iCAMhL.jpg",
    "adult": false,
    "overview": "Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
    "release_date": "2018-05-15"
  }, {
    "vote_count": 5065,
    "id": 62,
    "video": false,
    "vote_average": 8,
    "title": "2001: A Space Odyssey",
    "popularity": 22.391,
    "poster_path": "/90T7b2LIrL07ndYQBmSm09yqVEH.jpg",
    "original_language": "en",
    "original_title": "2001: A Space Odyssey",
    "genre_ids": [878, 9648, 12],
    "backdrop_path": "/6gyZF4SeifiUUYDELkCS8nOqsu2.jpg",
    "adult": false,
    "overview": "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced super computer.",
    "release_date": "1968-04-09"
  }, {
    "vote_count": 2,
    "id": 493003,
    "video": false,
    "vote_average": 8.8,
    "title": "A Boy. A Girl. A Dream",
    "popularity": 10.384,
    "poster_path": "/sV0nhp3NbDWOzK5kWDXFrFNkODo.jpg",
    "original_language": "en",
    "original_title": "A Boy. A Girl. A Dream",
    "genre_ids": [10749],
    "backdrop_path": "/e0ZRCSbjCFa8dhzVot42SnKDxhX.jpg",
    "adult": false,
    "overview": "On the night of the 2016 Presidential election, Cass, an L.A. club promoter, takes a thrilling and emotional journey with Frida, a Midwestern visitor. She challenges him to revisit his broken dreams - while he pushes her to discover hers.",
    "release_date": "2018-01-22"
  }, {
    "vote_count": 517,
    "id": 850,
    "video": false,
    "vote_average": 7.3,
    "title": "A Christmas Story",
    "popularity": 20.092,
    "poster_path": "/1dSFarRSXwMjFODxPTwyaiNZotF.jpg",
    "original_language": "en",
    "original_title": "A Christmas Story",
    "genre_ids": [35, 10751],
    "backdrop_path": "/wok0YepwQfBAPsrttFq0W6HXT2g.jpg",
    "adult": false,
    "overview": "The comic mishaps and adventures of a young boy named Ralph, trying to convince his parents, teachers, and Santa that a Red Ryder B.B. gun really is the perfect Christmas gift for the 1940s.",
    "release_date": "1983-11-18"
  }, {
    "vote_count": 236,
    "id": 13187,
    "video": false,
    "vote_average": 7.6,
    "title": "A Charlie Brown Christmas",
    "popularity": 19.552,
    "poster_path": "/3Bn0tc1BsheZwUQtvl10wTgQ16J.jpg",
    "original_language": "en",
    "original_title": "A Charlie Brown Christmas",
    "genre_ids": [16, 10751, 35, 10770],
    "backdrop_path": "/rtPtwVTo4RqumivX2zspSk8GyCy.jpg",
    "adult": false,
    "overview": "When Charlie Brown complains about the overwhelming materialism that he sees amongst everyone during the Christmas season, Lucy suggests that he become director of the school Christmas pageant. Charlie Brown accepts, but is a frustrating struggle. When an attempt to restore the proper spirit with a forlorn little fir Christmas tree fails, he needs Linus' help to learn the meaning of Christmas.",
    "release_date": "1965-12-09"
  }, {
    "vote_count": 3562,
    "id": 37735,
    "video": false,
    "vote_average": 6.8,
    "title": "Easy A",
    "popularity": 8.875,
    "poster_path": "/1pgPO3OfSm2inpODMqg2RNmLW90.jpg",
    "original_language": "en",
    "original_title": "Easy A",
    "genre_ids": [35],
    "backdrop_path": "/wu4tawMznxUvqP21lUH6RKrv3LQ.jpg",
    "adult": false,
    "overview": "Olive, an average high school student, sees her below-the-radar existence turn around overnight once she decides to use the school's gossip grapevine to advance her social standing. Now her classmates are turning against her and the school board is becoming concerned, including her favorite teacher and the distracted guidance counselor. With the support of her hilariously idiosyncratic parents and a little help from a long-time crush, Olive attempts to take on her notorious new identity and crush the rumor mill once and for all.",
    "release_date": "2010-09-16"
  }, {
    "vote_count": 803,
    "id": 431530,
    "video": false,
    "vote_average": 6.2,
    "title": "A Bad Moms Christmas",
    "popularity": 18.881,
    "poster_path": "/gPNHolu7AGnrB7r5kvJRRTfwMFR.jpg",
    "original_language": "en",
    "original_title": "A Bad Moms Christmas",
    "genre_ids": [35],
    "backdrop_path": "/aIF2xRhE7iGxQd6ITGNrwYdGB9e.jpg",
    "adult": false,
    "overview": "Amy, Kiki and Carla – three under-appreciated and over-burdened women – rebel against the challenges and expectations of the Super Bowl for mothers: Christmas. And if creating a more perfect holiday for their families wasn’t hard enough, they have to do all of that while hosting and entertaining their own mothers.",
    "release_date": "2017-11-01"
  }, {
    "vote_count": 282,
    "id": 11257,
    "video": false,
    "vote_average": 7.1,
    "title": "A Room with a View",
    "popularity": 8.633,
    "poster_path": "/fS4mDKBIHeTmWXPGgz64d2dMyJG.jpg",
    "original_language": "en",
    "original_title": "A Room with a View",
    "genre_ids": [18, 10749],
    "backdrop_path": "/8fAXEcTr8AlHsZl6kXKMBXKeqs0.jpg",
    "adult": false,
    "overview": "When Lucy Honeychurch and chaperon Charlotte Bartlett find themselves in Florence with rooms without views, fellow guests Mr Emerson and son George step in to remedy the situation. Meeting the Emersons could change Lucy's life forever but, once back in England, how will her experiences in Tuscany affect her marriage plans?",
    "release_date": "1985-12-13"
  }, {
    "vote_count": 8,
    "id": 488067,
    "video": false,
    "vote_average": 5.2,
    "title": "A Royal Christmas Ball",
    "popularity": 17.282,
    "poster_path": "/3WyIHLtUPSpVFAiWMEc7GKU3Qc3.jpg",
    "original_language": "en",
    "original_title": "A Royal Christmas Ball",
    "genre_ids": [10770, 10749],
    "backdrop_path": "/6VR6jdrlif2vAP0G57Zzy8OmOPK.jpg",
    "adult": false,
    "overview": "Dateless for the Christmas ball, 39-year-old bachelor, King Charles of Baltania, tracks down his American college sweetheart, only to discover Allison has never been married, yet raised a 17-year-old daughter, Lily, who mathematically might be Charles' biological princess.",
    "release_date": "2017-12-10"
  }, {
    "vote_count": 1736,
    "id": 1585,
    "video": false,
    "vote_average": 8.2,
    "title": "It's a Wonderful Life",
    "popularity": 30.228,
    "poster_path": "/rgj6QjdyCeDrO9KGt1kusGyhvb2.jpg",
    "original_language": "en",
    "original_title": "It's a Wonderful Life",
    "genre_ids": [18, 10751, 14],
    "backdrop_path": "/nMomMy1sD3SN2QsKop3zBXCJfDJ.jpg",
    "adult": false,
    "overview": "A holiday favourite for generations...  George Bailey has spent his entire life giving to the people of Bedford Falls.  All that prevents rich skinflint Mr. Potter from taking over the entire town is George's modest building and loan company.  But on Christmas Eve the business's $8,000 is lost and George's troubles begin.",
    "release_date": "1946-12-20"
  }, {
    "vote_count": 4265,
    "id": 9487,
    "video": false,
    "vote_average": 6.9,
    "title": "A Bug's Life",
    "popularity": 12.445,
    "poster_path": "/u9qGMRwcPwP0WETxulS5hKUsEum.jpg",
    "original_language": "en",
    "original_title": "A Bug's Life",
    "genre_ids": [12, 16, 35, 10751],
    "backdrop_path": "/bHMHpXNjeKRxcjWcpbIAD5f0aIK.jpg",
    "adult": false,
    "overview": "On behalf of \"oppressed bugs everywhere,\" an inventive ant named Flik hires a troupe of warrior bugs to defend his bustling colony from a horde of freeloading grasshoppers led by the evil-minded Hopper.",
    "release_date": "1998-11-25"
  }, {
    "vote_count": 5770,
    "id": 185,
    "video": false,
    "vote_average": 8.2,
    "title": "A Clockwork Orange",
    "popularity": 16.411,
    "poster_path": "/4sHeTAp65WrSSuc05nRBKddhBxO.jpg",
    "original_language": "en",
    "original_title": "A Clockwork Orange",
    "genre_ids": [878, 18],
    "backdrop_path": "/unMc1jEyqCnzba976GviSFKGagt.jpg",
    "adult": false,
    "overview": "Demonic gang-leader Alex goes on the spree of rape, mugging and murder with his pack of \"droogs\". But he's a boy who also likes Beethoven's Ninth and a bit of \"the old in-out, in-out\". He later finds himself at the mercy of the state and its brainwashing experiment designed to take violence off the streets.",
    "release_date": "1971-12-18"
  }, {
    "vote_count": 91,
    "id": 448776,
    "video": false,
    "vote_average": 6.6,
    "title": "A Prayer Before Dawn",
    "popularity": 16.124,
    "poster_path": "/73KrcLh1DpnBP3HwGpqoUUwKWF4.jpg",
    "original_language": "en",
    "original_title": "A Prayer Before Dawn",
    "genre_ids": [18, 28, 80],
    "backdrop_path": "/tyaVwOLIpAzZFP0qmXm2VZhYkxZ.jpg",
    "adult": false,
    "overview": "The true story of Billy Moore, an English boxer incarcerated in Thailand's most notorious prison. Thrown into a world of drugs and violence, he finds his best chance to escape is to fight his way out in Muay Thai tournaments.",
    "release_date": "2018-06-20"
  }
];
